AWSTemplateFormatVersion: '2010-09-09'
Description: Application Stack
Parameters:
  ServiceName:
    Type: String
  # DBInstanceType:
  #   Description: Instance Type size parameter
  #   Type: String
  #   Default: db.m6i.large
  # DBSnapshotIdentifier:
  #   Description: (OPTIONAL) Snapshot identifier to restore the RDS database from
  #   Type: String
  #   Default: ''
  # EnableEnhancedMonitoring:
  #   Description: Provide metrics in real time for the operating system (OS) that your DB instance runs on.
  #   Type: String
  #   AllowedValues:
  #     - true
  #     - false
  #   Default: true
  VPCId:
    Description: VPC ID from Networking
    Type: String
    Default: ''  
  SubnetId1:
    Description: Subnet1 having internet gateway access
    Type: String
    Default: ''  
  SubnetId2:
    Description: Subnet2 having internet gateway access
    Type: String
    Default: ''  
  EC2AMI:
    Description: AMI for EC2 instance to deploy
    Type: String
    Default: ''
  EC2InstanceType:
    Description: Instance Type size parameter
    Type: String
    Default: t2.micro
  EC2VolumeSize:
    Description: Volume size of the EC2
    Type: String
    Default: '30'
Resources:

  # RDS:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: rds/rds.yaml
  #     Parameters:
  #       Stage: !Ref 'Stage'
  #       VPCId: !GetAtt 'Network.Outputs.VpcId'
  #       EnableEnhancedMonitoring: !Ref 'EnableEnhancedMonitoring'
  #       BackupRetentionPeriod: !Ref 'BackupRetentionPeriod'
  #       DBSnapshotIdentifier: !Ref 'DBSnapshotIdentifier'
  #       HostedZoneId: '{{resolve:ssm:HostedZoneId}}'
  #       ServiceName: !Ref 'ServiceName'
  #       SubnetA: !GetAtt 'Network.Outputs.PrivateSubnetIdA'
  #       SubnetB: !GetAtt 'Network.Outputs.PrivateSubnetIdB'
  #       DBInstanceType: !Ref 'DBInstanceType'
  #       AlertTopic: !GetAtt 'SnsTopic.Outputs.Topic'
  ALB:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W3002
          reason: "W3002: This code may only work with `package` cli command as the property"
    Properties:
      TemplateURL: alb/alb.yaml
      Parameters:
        ApplicationPort: '80'
        HealthCheckPort: '80'
        VPCId: !Ref 'VPCId'
        TargetInstanceId1: !GetAtt 'EC2Instance1.Outputs.EC2Id'
        TargetInstanceId2: !GetAtt 'EC2Instance2.Outputs.EC2Id'
        SubnetId1: !Ref SubnetId1
        SubnetId2: !Ref SubnetId2
        AlbSecurityGroupId: !GetAtt 'ALBSecurityGroup.Outputs.SecurityGroupId'

  ALBSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W3002
          reason: "W3002: This code may only work with `package` cli command as the property"
    Properties:
      TemplateURL: alb/alb_secgrp.yaml
      Parameters:
        ServiceName: !Ref 'ServiceName'
        VPCId: !Ref VPCId

  EC2Instance1:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W3002
          reason: "W3002: This code may only work with `package` cli command as the property"    
    Properties:
      TemplateURL: ec2/ec2.yaml
      Parameters:
        VPCId: !Ref VPCId
        EC2AMI: !Ref 'EC2AMI'
        ServiceName: !Ref 'ServiceName'
        SubnetId1: !Ref SubnetId1
        EC2InstanceType: !Ref 'EC2InstanceType'
        EC2VolumeSize: !Ref 'EC2VolumeSize'
        ServerName: WebServer1
        ALBSecurityGroup: !GetAtt ALBSecurityGroup.Outputs.SecurityGroupId

  EC2Instance2:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W3002
          reason: "W3002: This code may only work with `package` cli command as the property"    
    Properties:
      TemplateURL: ec2/ec2.yaml
      Parameters:
        VPCId: !Ref VPCId
        EC2AMI: !Ref 'EC2AMI'
        ServiceName: !Ref 'ServiceName'
        SubnetId1: !Ref SubnetId2
        EC2InstanceType: !Ref 'EC2InstanceType'
        EC2VolumeSize: !Ref 'EC2VolumeSize'
        ServerName: WebServer2
        ALBSecurityGroup: !GetAtt ALBSecurityGroup.Outputs.SecurityGroupId
